version: "3.9"
services:
  reverse-proxy:
    image: traefik:2.5
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      # Used for the Traefik dashboard
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
