version: "3.9"
services:
  reverse-proxy:
    image: traefik:2.6
    command:
      # Enables the Traefik dashboard insecurely
#      - --api.insecure=true
      # Sets the log level
      - --log.level=DEBUG
      # Ports used for http & https
      - --entryPoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      # Enables Docker integration and prevents containers from inadvertent exposure
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.file.directory=/configuration
      - --providers.file.watch=true
    labels:
      traefik.enable: true
      # Global redirection: all subdomains for http
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    # Used for the Traefik dashboard
#      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf:/configuration
      - ./certs/${PROJECT_DOMAIN_NAME}.pem:/etc/ssl/private/tls-crt.pem:ro
      - ./certs/${PROJECT_DOMAIN_NAME}-key.pem:/etc/ssl/private/tls-key.pem:ro
    environment:
      - TRAEFIK_DOMAIN=${PROJECT_DOMAIN_NAME}

networks:
  default:
    name: traefik-proxy
    external: true
