version: "3.9"
services:
  reverse-proxy:
    image: traefik:2.5
    command: --providers.docker --api.insecure=true
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      # Used for the Traefik dashboard
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: traefik-proxy
    external: true
