version: "3.9"
services:
  reverse-proxy:
    image: traefik:2.6
    command:
      # Enables the Traefik dashboard insecurely
#      - --api.insecure=true
      # Sets the log level
      - --log.level=DEBUG
      # Ports used for http & https
      - --entryPoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      # Enables Docker integration and prevents containers from inadvertent exposure
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.file.directory=/configuration
      - --providers.file.watch=true
    labels:
      traefik.enable: true
      # Global redirection: all subdomains for http
      traefik.http.routers.http-other-subdomains-catchall.rule: HostRegexp(`{subhost:(?:[a-z]+)}.trevthedev.localhost`)
      traefik.http.routers.http-other-subdomains-catchall.entrypoints: web
      traefik.http.routers.http-other-subdomains-catchall.middlewares: redirect-to-secure-subdomains
      # Global redirection: base domain for http
      traefik.http.routers.http-base-domain-catchall.rule: Host(`trevthedev.localhost`)
      traefik.http.routers.http-base-domain-catchall.entrypoints: web
      traefik.http.routers.http-base-domain-catchall.middlewares: redirect-to-secure-base-domain
      # Global redirection: base domain for https
      traefik.http.routers.https-base-domain-catchall.tls: true
      traefik.http.routers.https-base-domain-catchall.rule: Host(`trevthedev.localhost`)
      traefik.http.routers.https-base-domain-catchall.entrypoints: web-secure
      traefik.http.routers.https-base-domain-catchall.middlewares: redirect-to-secure-base-domain
      # Middleware: Redirect to secure base domain
      traefik.http.middlewares.redirect-to-secure-base-domain.redirectregex.regex: ^https?://(?:www\.)?(.+)
      traefik.http.middlewares.redirect-to-secure-base-domain.redirectregex.replacement: https://www.$${1}
      traefik.http.middlewares.redirect-to-secure-base-domain.redirectregex.permanent: true
      # Middleware: Redirect to secure subdomains
      traefik.http.middlewares.redirect-to-secure-subdomains.redirectregex.regex: ^https?://(.+)
      traefik.http.middlewares.redirect-to-secure-subdomains.redirectregex.replacement: https://$${1}
      traefik.http.middlewares.redirect-to-secure-subdomains.redirectregex.permanent: true
    configs:
      - source: traefik-certificates
        target: /configuration/certificates.yml
    secrets:
      - source: tls_cert
        target: /etc/ssl/private/tls_crt
      - source: tls_key
        target: /etc/ssl/private/tls_key
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    # Used for the Traefik dashboard
#      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/:/configuration/

networks:
  default:
    name: traefik-proxy
    external: true

configs:
  traefik-certificates:
    file: conf/certificates.yml

secrets:
  tls_cert:
    file: certs/trevthedev.localhost.pem
  tls_key:
    file: certs/trevthedev.localhost-key.pem
